services:
  # php-nginx
  # nginx and php are running as user: 'nobody'
  php-nginx:
    image: trafex/php-nginx
    container_name: php-nginx
    restart: always
    expose:
      - 8080
    ports:
      - ${PORT_PHP_NGINX}:8080
    volumes:
      # default site
      - ./frontend/web_php/html:/var/www/html
      # nginx settings
      - ./frontend/web_php/nginx-php-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/web_php/nginx-php-config/sites-enabled/site.conf:/etc/nginx/conf.d/site.conf
      # php settings
      - ./frontend/web_php/nginx-php-config/php-custom.ini:/etc/php81/conf.d/php-custom.ini
      # php fpm settings
      - ./frontend/web_php/nginx-php-config/php-custom-fpm-settings.conf:/etc/php81/php-fpm.d/server.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-php.rule=Host(`${SUBDOMAIN_PHP}${DOMAIN}`)"
      - "traefik.http.routers.web-php.entrypoints=websecure"
      - "traefik.http.routers.web-php.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-php.loadbalancer.server.port=8080"
    networks:
      - backnet
    # depends_on:
    #  - db