services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    environment:
      - TZ=${TZ}
    # ports:
    #  - "${PORT_NODERED}:1880"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`${SUBDOMAIN_NODERED}${DOMAIN}`)"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.http.routers.nodered.tls.certresolver=letsencrypt"
    volumes:
      - ./.node-red:/data
    # not sure if command: works
    command:
      - /bin/sh
      - -c
      - |
        chmod o+w /data
    networks:
      - backnet




